name: CI/CD Release Pipeline
on: 
  push:
    branches:
      - main
jobs:
  build-hugo:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}
           
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build Project
        run: hugo --minify

      - name: Release Assets
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          personal_token: ${{ secrets.TOKEN }}
          publish_dir: ./public
      
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_TF_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_TF_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TF_TENANT_ID }}
      TF_VERSION: 1.6.4
    runs-on: ubuntu-latest
    needs: build-hugo
    environment: production
  
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}
    
      - name: 'Terraform fmt'
        id: fmt
        run: terraform fmt -check
    
      - name: 'Terraform init'
        id: init
        run: |
          set -a
          source ../.env.backend
          terraform init \
            -backend-config="resource_group_name=$TF_VAR_state_resource_group_name" \
            -backend-config="storage_account_name=$TF_VAR_state_storage_account_name"

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
    
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
    
      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve

  upload-files:
    env:
      WORKING_DIRECTORY: .
    runs-on: ubuntu-latest
    needs: [build-hugo, terraform]
    steps:
    
      - name: Azure Login
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Upload Assets To Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch -d "\$web" -s ${{ env.WORKING_DIRECTORY }}/public --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" --overwrite true
                       
      - name: Purge Azure CDN Resources
        run:
          az cdn endpoint purge -n ${{ secrets.AZURE_CDN_ENDPOINT }} --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} --content-paths "/*" --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --no-wait
             
      - name: Dispose Azure Service Principal Session
        run: |
          az logout
